### ISSUE TITLE
 Taakverdeling en notities van wekelijkse meetings

### ISSUE THREAD

**Issue by yannickdoteu** [cbouwen/transcendence#2]
# Vrijdag 22 november

## Taakverdeling

**Bastian**
 - [ ] Another game
 
**Bram**
- [ ] Live chat

**Cedric**
- [ ] Pong
- [ ] Database
- [ ] AI opponent
- [x] Deployment via Docker Compose (#3)
- [ ] User management and authentication

**Matisse**
- [ ] Multi language
- [ ] User management and authentication
- [ ] Tournament

**Yannick**
- [ ] 2FA
- [x] Remote auth

**Iedereen**
- [ ] Browser compatibility
- [ ] Django
- [ ] Single Page Application
- [ ] Bootstrap

![photo_2024-11-22 14 56 48](https://github.com/user-attachments/assets/69c8a8be-b9d0-44e8-abed-5ed2291e7b7f)
![photo_2024-11-22 14 56 53](https://github.com/user-attachments/assets/452fa31e-7d07-4739-b365-bb53fc07717c)
![photo_2024-11-22 14 56 56](https://github.com/user-attachments/assets/c87c8e81-4542-4efa-b1af-f6c0da822e02)

# Maandag 2 december

## Todo's

- [ ] Volgende meeting plannen (9 december)
- [ ] Issue aanmaken voor volgende meeting

**Comment by yannickdoteu** [comment]
@cbouwen kun je checken of de taakverdeling klopt met hoe ik het heb opgeschreven?
